[env:bw_swan_r5]
platform = ststm32
board = bw_swan_r5
framework = arduino
monitor_speed = 9600


upload_protocol = dfu
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
    -D USBD_VID=0x0483
    -D USBD_PID=0x5740
    -D USB_MANUFACTURER="Blues Wireless"
    -D USB_PRODUCT="\"Blues Swan R5\""

lib_deps = 
    bblanchon/ArduinoJson